[package]
name = "dsn-traveller"
version = "0.1.0"
license = "AGPL-3.0-or-later"
authors = ["Florian Jacob <projects+git@florianjacob.de>"]

[dependencies]
futures-await = { git = "https://github.com/alexcrichton/futures-await" }
tokio-core = "0.1"
futures-timer = "0.1"
url = "1"
hyper = "0.11"
hyper-tls = "0.1"
clap = "2"
petgraph = { version = "0.4", features = ["graphmap", "serde-1"] }
petgraph-graphml = "1"
hostname = "0.1"
rand = "0.5"
matrixgraph = { path = "matrixgraph" }

serde = "1"
serde_derive = "1"
serde_json = "1"
url_serde = "0.2"
ron = "0.2"
regex = "0.2"
lazy_static = "1"

[dependencies.ruma-client]
git = "https://github.com/florianjacob/ruma-client"
branch = "supercombiner"

[dependencies.ruma-events]
git = "https://github.com/florianjacob/ruma-events"
branch = "supercombiner"

[dependencies.ruma-identifiers]
git = "https://github.com/ruma/ruma-identifiers"
branch = "synapse-workarounds"

[patch.crates-io]
ruma-events = { git = 'https://github.com/florianjacob/ruma-events', branch = 'supercombiner' }
ruma-identifiers = { git = 'https://github.com/ruma/ruma-identifiers', branch = 'synapse-workarounds' }
